### PR TITLE
[C++] Minimum Spanning Tree (Kruskal's Algorithm & Prim's Algorithm)

### PR DESCRIPTION
**Pull request by rafu01**
Greedy algorithms: Prims and Kruskal were added. 
Followed the guidelines
gave proper comments and examples

### CODE REVIEW

**Review by amanmehara — APPROVED** [review]
Thanks for contributing! 🎉

**Comment by rafu01** [comment]
Thank you so much

**Comment by rafu01** [comment]
Can you add hactober_accepted tag so that it will get accepted?

**Comment by amanmehara** [comment]
@rafu01 
There is no need to add **hacktoberfest-accepted**. 

See https://hacktoberfest.digitalocean.com/details
  ```
Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
```

**Comment by rafu01** [comment]
Okay thank you so much

**Pull request merged**
