### PR TITLE
[C] Infix to Postfix (Expression Transformation)

### PR DESCRIPTION
**Pull request by Ramjonchhen**
Infix to Post fix expression  written in c.

### CODE REVIEW

**Review by amanmehara — CHANGES_REQUESTED** [review]
Please add the Apache license header also at the top of the file.

Similar to this: https://github.com/amanmehara/programming/blob/master/C/Bankers%20Algorithm/bankersAlgorithm.c

**Comment by Ramjonchhen** [comment]
sure looking forward towards it.

**Comment by Ramjonchhen** [comment]
I added the apache liscene header. Can you please once look at the changes and comment if more changes are required.

**Review by amanmehara — APPROVED** [review]
Thanks for contributing! 🎉

**Pull request merged**
