### PR TITLE
[Python]K means

### PR DESCRIPTION
**Pull request by premalrupnur**
Implemented K-means algorithm on random data created using numpy

### CODE REVIEW

**Review by amanmehara — CHANGES_REQUESTED** [review]
Please remove gradient descent related file form the source!

**Comment by premalrupnur** [comment]
> Please remove gradient descent related file form the source!

Do you mean from master branch but why

**Comment by premalrupnur** [comment]
Or from my branch

**Comment by amanmehara** [comment]
@premalrupnur in these changes I can see the Gradient Descent file also.
That file is already merged in #172, so no need for adding it again in this PR.

**Comment by premalrupnur** [comment]
> @premalrupnur in these changes I can see the Gradient Descent file also.
> That file is already merged in #172, so no need for adding it again in this PR.

yeah I would remove it , but in commit I dont see that file

**Comment by premalrupnur** [comment]
If remove it , ig it would count as commit and merging would delete it

**Comment by premalrupnur** [comment]
But really I am not able see the file  as a commit in commits

**Comment by amanmehara** [comment]
> But really I am not able see the file as a commit in commits

Simply create a new branch, add K Means source file only. And create a new PR.
Then I'll close this one and merge the new one.

**Pull request closed without merging**
