### PR TITLE
Linear Search added

### PR DESCRIPTION
**Pull request by KartikeySharma**

### CODE REVIEW

**Review by amanmehara — CHANGES_REQUESTED** [review]
You deleted the already existing binary search implementation. :sob:

Please add it back!

Also, have a look at https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md

**Comment by KartikeySharma** [comment]
I didn't delete your binary search implementation. I just changed the search.h as I thought it was for the linear search. I will change it back and will add my linear search file differently. Ok?

**Comment by KartikeySharma** [comment]
Pls have a look at the below pull request
Added Linear Search Algorithm #99.

You can merge that pull request and close this one :)

**Comment by amanmehara** [comment]
Closing in favor of #99 .

**Comment by KartikeySharma** [comment]
Ok. 👍

**Pull request closed without merging**
