### PR TITLE
[Julia] Hello World & Syntax

### LINKED ISSUE #84: Algorithms, Code Snippets & Data Structures Implemented in Julia.
I did not find any code snippets for Julia Language.

It is a relatively new language and it is being used by many and it should be added.

I will make a PR to add this.

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Added Julia Language folder and some code snippets. 

Will add more in the coming days.

This PR fixes #84

### CODE REVIEW

**Comment by amanmehara** [comment]
Please have a look at https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md and make changes accordingly.
I'll approve and merge afterwards! :smiley:

**Comment by navendu-pottekkat** [comment]
@amanmehara Sure I will make the changes

**Comment by navendu-pottekkat** [comment]
@amanmehara Here are the changes I made 

Changed Tabs to spaces
Added newline at the end

Should I make any more changes?

**Comment by amanmehara** [comment]
Yes, please add the Apache license header to your code as well.
Having year 2020 and copyright owner as your name.

**Comment by navendu-pottekkat** [comment]
@amanmehara made the changes

**Pull request merged**
