### PR TITLE
[Python] FizzBuzz

### PR DESCRIPTION
**Pull request by abumaz**
@amanmehara, I have added the file for FizzBuzz and made sure that they satisfy the guidelines given and optimized the code for readability, added comments, and made it suitable for further addition of numbers other than 3 and 5.

### CODE REVIEW

**Review by amanmehara — CHANGES_REQUESTED** [review]
Please use **fizz_buzz** (snake_case 🐍 ) instead of **FizzBuzz** or **fizzBuzz** (camel_case 🐫 ).
Also, rename the directory and file name accordingly!

I'll approve once you fix it.

**Comment by abumaz** [comment]
I have made the required changes. Thanks for giving me the opportunity to contribute.

**Comment by abumaz** [comment]
Hey @amanmehara, please check out the changes that I have made and approve this pull if they satisfy all the criteria. If I must make any further changes, please inform me of the same.

**Review by amanmehara — APPROVED** [review]
Thanks for contributing! 🎉

**Pull request merged**
