### PR TITLE
[Python] Dijkstra's Algorithm & Quick Sort

### PR DESCRIPTION
**Pull request by anoop447**
added dijkstars shortest path finding algorithm using python

### CODE REVIEW

**Comment by anoop447** [comment]
also added quicksort

**Comment by amanmehara** [comment]
Please have a look at https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md and make changes accordingly.
I'll approve and merge afterwards! 😃

**Comment by anoop447** [comment]
I have modified the changes as required.
please do check if anything else is required.

**Review by amanmehara — APPROVED** [review]
Thanks for contributing! 🎉

**Pull request merged**
