### PR TITLE
[C++] Competitive (Codechef)

### PR DESCRIPTION
**Pull request by TheShubham-K**

### CODE REVIEW

**Review by amanmehara — CHANGES_REQUESTED** [review]
Thanks for contributing! 🎉 

Please remove all the files except source files. (i.e. **.cpp** files)

**Comment by TheShubham-K** [comment]
> Thanks for contributing! 🎉
> 
> Please remove all the files except source files. (i.e. **.cpp** files)

ohh Sure

**Review by amanmehara — APPROVED** [review]
Thanks for contributing! 🎉

**Comment by TheShubham-K** [comment]
You're Welcome

**Pull request merged**
